### ISSUE TITLE
Issue with Writing own checks

### ISSUE THREAD

**Issue by yogeshkoli** [spatie/laravel-server-monitor#100]
Hello,

I have written custom check to find out the disk space storage from EFS, however I am getting InvalidCheckDefinition.php Error.

Here is the error message:

**The check with id `11` has an unknown type `efsstorage`. Valid values are apache, diskspace, elasticsearch, memcached, mysql**

Is there any thing extra needed apart from registering class into config file after creating custom class which is extends from Spatie\ServerMonitor\CheckDefinitions\CheckDefinition. ?

Please let me know.

**Comment by freekmurze** [comment]
What does `config('server-monitor')` return?

**Comment by yogeshkoli** [comment]
@freekmurze I get it thank you it was cache issue. i had to execute following command and then it works out of the box.

`php artisan config:cache`

Thanks!
