### ISSUE TITLE
Running Locally

### ISSUE THREAD

**Issue by sicaboy** [spatie/laravel-server-monitor#108]
Hi guys, 
I know this ticket is a bit of duplicated, but as I cannot use another server to monitor due to security compliance. I'm looking to find a way to install the server-monitor-app locally so that I just hope it to execute to check local free space and send slack message. Do you guys have any idea if it's possible to achieve?  Cheers

**Comment by vladan-me** [comment]
I believe it's possible, two things are required:

1. create a file in your project like below

```
<?php

namespace App\Utilities;

use Spatie\ServerMonitor\Manipulators\Manipulator;
use Spatie\ServerMonitor\Models\Check;
use Symfony\Component\Process\Process;


class ManipulatorLocal implements Manipulator
{
    public function manipulateProcess(Process $process, Check $check): Process
    {
        $process->setCommandLine($check->getDefinition()->command());
        return $process;
    }
}
```

2. Add this class in `config/server-monitor.php` as a `process_manipulator` hook

```
    /*
     * Right before running a check it's process will be given to this class. Here you
     * can perform some last minute manipulations on it before it will
     * actually be run.
     *
     * This class should implement Spatie\ServerMonitor\Manipulators\Manipulator
     */
    'process_manipulator' => App\Utilities\ManipulatorLocal::class, 
```

A side note, this will make all commands run locally, but you can get creative in `ManipulatorLocal` class and suit it for your needs.

**Comment by vladan-me** [comment]
In the latest version 1.9 instead of

`$process->setCommandLine($check->getDefinition()->command());
`

change to

`$process = Process::fromShellCommandline($check->getDefinition()->command());
`

**Comment by piotrgulbis** [comment]
I just created a 'localhost' host in server-monitor:add-host with my user.

To get this to work I used ssh-keygen to create my ssh keys, then used

`ssh-copy-id  user@localhost`

After this step all the checks worked.
