### ISSUE TITLE
Package doesn't work with PHP 7.3 and Laravel 8

### ISSUE THREAD

**Issue by paras-malhotra** [spatie/laravel-server-monitor#112]
Thanks for the awesome package! :heart:

1.9.2 is the only version that supports Laravel 8 but it requires Laravel Blink. Blink 1.4.1 is the only version that supports Laravel 8 but that requires PHP 7.4.

**Comment by freekmurze** [comment]
Please create a fork of the package that is compatible with your environment. After you've upgraded to PHP 7.4, switch back to the spatie version.

**Comment by gwrit** [comment]
Great support 👍
