### ISSUE TITLE
Incompatibility with PHP8, Laravel 8 or Composer 2?

### ISSUE THREAD

**Issue by gwrit** [spatie/laravel-server-monitor#113]
`
[InvalidArgumentException]                                                                                                           
  Package spatie/laravel-server-monitor has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
`

My environment:

Composer:
`
Composer version 2.0.8 2020-12-03 17:20:38
`

PHP:

`
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
`

Laravel:

`
v8.21.0
`

**Comment by freekmurze** [comment]
Feel free to send a PR that adds compatilbility with PHP 8, make sure the tests run on PHP 8 as well.
