### ISSUE TITLE
Host SSH Key Paths

### ISSUE THREAD

**Issue by mattcroftuk** [spatie/laravel-server-monitor#17]
Hey,

Would you guys consider adding the ability to specify where a hosts ssh key sits on the server, and then on the ssh connection, it passes the key via the `ssh -i`?

Thanks

**Comment by freekmurze** [comment]
Could you send a fully tested PR for this?

**Comment by freekmurze** [comment]
Actually scratch that. I've added `Manipulators` with which you can manipulate any `Process` before it'll run. More info in the docs soon.

**Comment by mattcroftuk** [comment]
Ah Thanks, i was also going to ask for a pre-process hook :) 

Look forward to the update.

**Comment by freekmurze** [comment]
Implemented: https://docs.spatie.be/laravel-server-monitor/v1/advanced-usage/manipulating-processes
