### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by sebestenyb** [spatie/laravel-server-monitor#21]
Hello,

Is it really require PHP7.1?
It only released a couple of month ago.
It's not part of the official repos for Ubuntu 16 yet.

Would you consider releasing that requirement?

Cheers, Sebi

**Comment by m1guelpf** [comment]
@sebestenyb https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/

**Comment by sebestenyb** [comment]
I'm aware of their PHP 7 policy. I'm taking about 7.1.
Also I know it's possible to upgrade, I'm just a little cautious to upgrade our servers to a version released only 3 month ago for the sake of one project.
Don't believe that 7.1 brought similar advantages as 7.0 did a year ago to justify forcing it.
But it was only a question.

**Comment by m1guelpf** [comment]
@sebestenyb The post says they force "the lastest PHP version".

**Comment by levidurfee** [comment]
I agree with @sebestenyb and don't think PHP 7.1 should be required. Doing things for the sake of doing things is usually a waste of time. Unless you can give a real reason, then you shouldn't enforce it.

Another suggestion, elaborate a little more on the commits, "commit" doesn't really tell us anything.

I'm happy to write my own server monitor and will most likely do so if the roadblocks mentioned above are not addressed.

Please don't take this as I am being rude, that is not the intention, I am simply trying to help.

**Comment by sebestenyb** [comment]
I appreciate the work Spatie does, their packages are very useful, and high quality ones.
I can also understand if the package uses some of the features only available in PHP 7.1, it's their decision, I use the package for free.
I don't want argue over the semantic analysis of a year old blog post.
I merely asked the question if it's possible to loosen the PHP requirement :)

**Comment by m1guelpf** [comment]
@sebestenyb You can always fork it and mantain a php 7 version...

**Comment by HDVinnie** [comment]
I appreciate the package but I also will pass on this since I prefer to stay with PHP 7 for now.

**Comment by freekmurze** [comment]
Hi, for all our newish projects we use PHP 7.1, so it for us it makes sense to use that PHP version of a minimum requirement for our packages as well. Like stated in the blogpost popularity is not our main goal, these packages are created primarly for use in our own projects / company.

So we'll probably never release a PHP 7.0 version of laravel-server-monitor. Like @m1guelpf already suggested, you're free to fork our code and maintain a PHP 7.0 compatible version yourself.

**Comment by hadi77makkawi** [comment]
is there a solution for PHP 7.0 then ?
