### ISSUE TITLE
Wrong notification route for mail

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-server-monitor#22]
Mail notifications currently do not work (check run hangs). See https://github.com/spatie/laravel-server-monitor/blob/master/src/Notifications/Notifiable.php, line 13. It references the uptime monitor, but should be:

``` php
return config('server-monitor.notifications.mail.to');
```

**Comment by freekmurze** [comment]
Fixed! Thanks for bringing this my attention.

**Comment by sebastiaanluca** [comment]
Thanks for the quick fix!
