### ISSUE TITLE
Unused migration imports

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-server-monitor#23]
In both `create_checks_table.php.stub` and `create_hosts_table.php.stub`, non-existing classes are imported (copy/paste from uptime monitor hmm? :p):

``` php
use Spatie\ServerMonitor\Models\Enums\CertificateStatus;
use Spatie\ServerMonitor\Models\Enums\UptimeStatus;
```

***

Also some minor errors in the docs, probably forgotten when refactoring classes. 

- https://docs.spatie.be/laravel-server-monitor/v1/monitoring-basics/writing-your-own-checks (resolve method, succeeded/succeed, …)

**Comment by freekmurze** [comment]
Fixed, thank for notifying me.

If you spot more errors in the docs, feel free to send a PR.
