### ISSUE TITLE
Migration error (Mariadb issue?)

### ISSUE THREAD

**Issue by sheldonkotyk** [spatie/laravel-server-monitor#26]
php artisan migrate 

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; chec
  k the manual that corresponds to your MariaDB server version for the right syntax to use near 'jso
  n null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: cre
  ate table `hosts` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not
  null, `ssh_user` varchar(255) null, `port` int null, `ip` varchar(255) null, `custom_properties` j
  son null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 col
  late utf8_unicode_ci)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; chec
  k the manual that corresponds to your MariaDB server version for the right syntax to use near 'jso
  n null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1

Brand new Valet install with mariadb.

I have your uptime monitor installed and working on this domain.

**Comment by sheldonkotyk** [comment]
Looks like it is due to mariabd not supporting json properly...
http://stackoverflow.com/questions/42425667/mariadb-json-support-in-laravel

Arg. Good thing I'm just setting up some new servers.
https://github.com/laravel/framework/issues/13622#issuecomment-221567026

**Comment by freekmurze** [comment]
Yup, `json` fields are only supported in MySQL. I did not test this but you could use `text` columns instead of `json` colums to make it work in MariaDB.

**Comment by navotera** [comment]
i have same error, but thank for your solution @freekmurze
