### ISSUE TITLE
Requires PHP 7.1?

### ISSUE THREAD

**Issue by KuenzelIT** [spatie/laravel-server-monitor#27]
Hey,

does the server monitor really require PHP 7.1 or could it also be run with PHP 7.0?

My problem is, that I'd like to run it on a Raspberry PI, which has 7.0.16.

Does the package require any of the new stuff from 7.1?

Thanks!

**Comment by KuenzelIT** [comment]
Sry, did't look into the closed issues.

**Comment by bbashy** [comment]
If you install php7.1-cli you can get this working since the package is all CLI based. That also shouldn't affect apps running on php7.0 via nginx/apache etc.
