### ISSUE TITLE
Usage Question: Dynamic Notificiation Email

### ISSUE THREAD

**Issue by mattcroftuk** [spatie/laravel-server-monitor#33]
When a notification is fired from the event listener, i can see that it calls the event required to handle this and passing in the event fired.

However it pulls the email from the config; weather thats a string or an array; and then it uses that address to send the email too. 

Is there any way that this email address can be dynamic and pulled from the check model or a relationship of that model?

My usage would require this to be pulled from the database depending on who that check is attached too.

I can't see any valid way of this due to the way the notifiable is constructed in the EventHandler class.

The simplest form of what i would require to make this work, would be along the lines off:

 in the `Spatie\ServerMonitor\Notifications\EventHandler` class

```
protected function determineNotifiable($event)
    {
        $notifiableClass = $this->config->get('server-monitor.notifications.notifiable');

        return app($notifiableClass)->setEvent($event);
    }
```

I am not suggesting that change, but hoping that helps portray where I'm trying to get too.

Is this something that you can implement? Even allowing a different `EventHandler` class to be specified would be helpful from the config.

Thanks.

**Comment by nipaTCM** [comment]
:+1:

**Comment by freekmurze** [comment]
I'd accept a PR with tests that adds this to the package.  @mattcroftuk your code sample show a good way on how to implement this.
