### ISSUE TITLE
[Feature request] Using ssh private keys 

### ISSUE THREAD

**Issue by morloderex** [spatie/laravel-server-monitor#34]
Hey @spatie 

Currently we can set a custom username to the host. It would be great if we also could set a custom ssh private key. 
Sense rebooting the monitor server can sometimes leave the ssh key's out of the ssh-agent. 
Leaving me choice but to log back in to the monitor server and re-add/attach the ssh-keys to the ssh-agent again. 

If we could use the optional `-i` flag in the ssh command along with a specified ssh key location then for the host defined we can then almost eliminate situations like this.

By doing this we could also avoid situations with too many ssh-key login tries in the ssh-agent. 

This would be useful if you have a lot of different ssh-keys.

**Comment by freekmurze** [comment]
I'd accept a non-breaking PR that adds this to the package.
