### ISSUE TITLE
Custom Database Table Names

### ISSUE THREAD

**Issue by apbassi89** [spatie/laravel-server-monitor#36]
Right now, the database table names are locked to `checks` and `hosts`. It's possible to override the `checks` model, which allows us to change the database table name, but there doesn't seem to be a way to do the same for `hosts`.

It would be very helpful if these table names could be customized, or at least if they were namespaced to avoid confusion with other models.

Thanks.

**Comment by freekmurze** [comment]
I'd accept a PR that makes the `host` model configurable in a non breaking way (cfr the `check` model).

**Comment by apbassi89** [comment]
Not sure what you mean by "cfr", but I've got PR #38 ready that's hopefully good to go

**Comment by freekmurze** [comment]
We'll handle this further in #38
