### ISSUE TITLE
Question : run monitor locally 

### ISSUE THREAD

**Issue by Te7a-Houdini** [spatie/laravel-server-monitor#48]
i want to ask if i can run **server-monitor:run-checks** command on my server that have the package installed , without making ssh

**Comment by freekmurze** [comment]
This package is designed to check remote hosts. Making local checks is not supported.

**Comment by qrazi** [comment]
I know this issue has been closed, but I was wondering if running check from local would not be a valid use case? I am thinking mostly about "check if website is alive" (didn't think so much yet about the actual criteria yet) type of checks.

I could try my hands on a PR? So to allow a check to execute it's command either locally or remotely?

**Comment by sebastiandedeyne** [comment]
@qrazi Sounds like you're looking for our uptime monitor: https://github.com/spatie/laravel-uptime-monitor

**Comment by qrazi** [comment]
@sebastiandedeyne Yes, you're right... 😅 I saw that package before, but kind of forgot about it when I wrote my comment on this issue. And I cannot think of another check I would like to run from local, so expect no PR... 😇😅 Thanks!
