### ISSUE TITLE
Multiple email recipients

### ISSUE THREAD

**Issue by Remo** [spatie/laravel-server-monitor#52]
I'm trying to define multiple email recipients, but using an array doesn't work because `Spatie\ServerMonitor\Notifications\Notifiable->routeNotificationForMail` returns a string and a comma separated string can't be used as a recipient.

From what I can see I could easily derive my own class, but I wonder whether this feature shouldn't be in the core?

**Comment by freekmurze** [comment]
If it's easy to code and testable and backwards compatible I'd accept a PR that enables mailing multiple recipients.

**Comment by Remo** [comment]
Not sure how to test this, but if anyone else wants to to this. Change this to a class of your own: https://github.com/spatie/laravel-server-monitor/blob/master/config/server-monitor.php#L56

and remove `string` as the return type or replace it with `array:

```php
public function routeNotificationForMail()
{
    return config('server-monitor.notifications.mail.to');
}
```

that way you can specify an array in this line and define multiple recipients https://github.com/spatie/laravel-server-monitor/blob/master/config/server-monitor.php#L45`
