### ISSUE TITLE
localhost support

### ISSUE THREAD

**Issue by dracoirs** [spatie/laravel-server-monitor#56]
I tried to do a bit of a work around so that the check didn't ssh when the host was named localhost but did not get it to work like I would have liked.  I thought I could manipulate the process command by setting the check value of isLocal to true but I believe I am missing some inheritance or something.  For the time being, I am just setting isLocal to true for all checks, meaning I can only do local checks for now, but I would like to ability to run commands on localhost without ssh'ing first.

Is my approach appropriate?  I think some built in functionality for avoiding ssh when on localhost would be handy.

`<?php

namespace App\Checks;

class LocalCheck extends \Spatie\ServerMonitor\Models\Check
{
    protected $isLocal = false;

    protected $table = 'checks';

    public function setLocal()
    {
        $this->isLocal = true;
    }

    public function getProcessCommand(): string
    {
        $delimiter = 'EOF-LARAVEL-SERVER-MONITOR';

        $definition = $this->getDefinition();

        if (!$this->isLocal) {
            $portArgument = empty($this->host->port) ? '' : "-p {$this->host->port}";

            $sshCommandSuffix = config('server-monitor.ssh_command_suffix');

            return "ssh {$this->getTarget()} {$portArgument} {$sshCommandSuffix} 'bash -se <<$delimiter" . PHP_EOL
          . 'set -e' . PHP_EOL
          . $definition->command() . PHP_EOL
          . $delimiter . "'";
        } else {
            return $definition->command();
        }
    }
}`

and manipulator
`<?php

namespace App\Checks;

use Spatie\ServerMonitor\Models\Check;
use Symfony\Component\Process\Process;

class ManipulatorLocal implements \Spatie\ServerMonitor\Manipulators\Manipulator
{
    public function manipulateProcess(Process $process, Check $check): Process
    {
        if (preg_match('/localhost/', $check->host->name)) {
            $check->setLocal();
            $check->getDefinition()->setCheck($check);
        }
        return $process;
    }
}`

**Comment by dracoirs** [comment]
Ok...Sorry about this.  I just saw I should just set the command line for the process in the manipulator like so:

`<?php

namespace App\Checks;

use Spatie\ServerMonitor\Models\Check;
use Symfony\Component\Process\Process;

class ManipulatorLocal implements \Spatie\ServerMonitor\Manipulators\Manipulator
{
    public function manipulateProcess(Process $process, Check $check): Process
    {
        if (preg_match('/localhost/', $check->host->name)) {
            $check->setLocal();
            $process->setCommandLine($check->getProcessCommand());
        }
        return $process;
    }
}
`

**Comment by herryswastika** [comment]
I have an error in my PuTTy console : Call to undefined method Illuminate\Database\Query\Builder::setLocal()

**Comment by munkiepus** [comment]
the solution here seems to work to run locally without ssh on localhost https://github.com/spatie/laravel-server-monitor/issues/108
