### ISSUE TITLE
Class 'Spatie\ServerMonitor\DateTime' not found

### ISSUE THREAD

**Issue by naveenyagati** [spatie/laravel-server-monitor#57]
when I'm runing **composer require spatie/laravel-server-monitor** in my fresh laravel installation,Im getting the following error

```
In ServerMonitorServiceProvider.php line 59:
Class 'Spatie\ServerMonitor\DateTime' not found
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
Installation failed, reverting ./composer.json to its original content.
```

**Comment by naveenyagati** [comment]
I have corrected this issue in my local development environment but it still needs to be fixed in this package

**Comment by freekmurze** [comment]
This has been fixed. 

Thank you for bringing this to my attention.
