### ISSUE TITLE
Make http ping check

### ISSUE THREAD

**Issue by marcteyssier** [spatie/laravel-server-monitor#59]
Hi,

I want to make a new check to test if a web page response.
So I don't want to make a ssh connection with command, but only guzzle call to check response (200 or 302 in some case).

Is it possible, because I don't see it in the code ?

Regards

**Comment by freekmurze** [comment]
Take a look at [spatie/laravel-uptime-montior](https://github.com/spatie/laravel-uptime-monitor)
