### ISSUE TITLE
Cannot use restricted shells

### ISSUE THREAD

**Issue by Muffinman** [spatie/laravel-server-monitor#68]
Hi, we'd like to be able to restrict the server monitor SSH commands to use `/bin/rbash` so we can be sure only a subset of predefined commands are available to be used by the monitor user.

At the moment it's hardcoded to send `bash` as the shell [here](https://github.com/spatie/laravel-server-monitor/blob/6986374acac417403c883464d9c7d9303054c4d4/src/Models/Concerns/HasProcess.php#L34) which makes this impossible at present. It would be nice if this were configurable such that it would be possible to specify the shell, or just run the command directly without the `bash` wrapper?

**Comment by freekmurze** [comment]
Feel free to send a PR with tests that adds a config option for this.

**Comment by Muffinman** [comment]
Thanks @freekmurze, glad to hear you are open to supporting this. I'll take a look at that PR when I have a few hours spare.
