### ISSUE TITLE
ssh passwords

### ISSUE THREAD

**Issue by pikkuhanuristi** [spatie/laravel-server-monitor#70]
How to use this with ssh -passwords?

If I run "php artisan server-monitor:run-checks" it's always - of course - asking user passwords.

php artisan server-monitor:run-checks
Start running 4 checks...
host-name: performing check `diskspace`...
host-name: performing check `elasticsearch`...
host-name: performing check `memcached`...
host-name: performing check `mysql`...
user@10.1.1.11's password: user@10.1.1.11's password: user@10.1.1.11's password: user@10.1.1.11's password: 
host-name: check `elasticsearch` failed

It asks password multible time and if I feed it nothing happens...

**Comment by Muffinman** [comment]
It's not possible afaik as this is meant to be an non-interactive tool. I expect will need to set up key authentication.
