### ISSUE TITLE
Fix error php5.6 deprecate need upgrade to 7.0.31

### ISSUE THREAD

**Issue by juanma386** [spatie/laravel-server-monitor#72]
![image](https://user-images.githubusercontent.com/15272380/45834372-4d91df80-bcdd-11e8-9105-375a076657e2.png)
Error Php 7.0.31

**Comment by freekmurze** [comment]
Please use PHP 7.1 or higher

https://github.com/spatie/laravel-server-monitor/blob/76cf99587af89773f7c75dfa0836a6ec58358bb6/composer.json#L19
