### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by futzlarson** [spatie/laravel-server-monitor#79]
This has been mentioned a couple other times:

https://github.com/spatie/laravel-server-monitor/issues/48
This was closed because he was looking for an uptime monitor.

https://github.com/spatie/laravel-server-monitor/issues/56
This sounds like a potential pull request - not sure why it was closed?

In my case, I was looking for a simple monitor for disk space because Linode doesn't provide it. Having used other spatie packages (activitylog, backup and permission - you all rock), I was excited to see that you had a solution for this as well. I didn't see any mention of running locally in the documentation but was hoping it might work anyway if I set the host to `localhost`. However, upon running `server-monitor:run-checks`, I get this:

```
$ a server-monitor:run-checks
Start running 2 checks...
localhost: performing check `diskspace`...
localhost: performing check `mysql`...
localhost: check `diskspace` failed
localhost: check `mysql` failed
All done!
```

And inspecting the `checks` table:

```
type: diskspace
status: failed
last_run_message: failed to run: Host key verification failed.
last_run_output: {"output": "", "exit_code": 255, "error_output": "Host key verification failed.\r\n", "exit_code_text": "Unknown error"}
```

All of which I'm sure is to be expected since @freekmurze said this in https://github.com/spatie/laravel-server-monitor/issues/48#issuecomment-332223461. I think it would be super useful if local checks were supported. I _could_ set up another server to do the checks remotely, but I would instead just find another solution that works locally. I'm happy to work on a PR for this as I've actually never contributed to open-source software. Especially since the solution seems to have already been written at https://github.com/spatie/laravel-server-monitor/issues/56.  Thoughts?

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that adds support for local checks to the package. Unfortunately I don't have the time to assist with creating this PR atm.

**Comment by futzlarson** [comment]
Sorry I didn't respond. I also don't have time; I ended up doing a scheduler job to check disk space instead.

**Comment by munkiepus** [comment]
there's a solution to get it running locally here https://github.com/spatie/laravel-server-monitor/issues/108
