### ISSUE TITLE
How to monitor ram

### ISSUE THREAD

**Issue by Cholowao** [spatie/laravel-server-monitor#83]

**Comment by freekmurze** [comment]
The package doesn't do this out of the box. You need to write your own check for that. https://docs.spatie.be/laravel-server-monitor/v1/monitoring-basics/writing-your-own-checks

**Comment by yogeshkoli** [comment]
@freekmurze I have added my own custom check but it is giving an error saying that 
`The check with id `11` has an unknown type `efsstorage`. Valid values are apache, diskspace, elasticsearch, memcached, mysql`

Is there any other configuration needed for custom checks?
