### ISSUE TITLE
Memcached check not working out of the box?

### ISSUE THREAD

**Issue by eduardocruz** [spatie/laravel-server-monitor#84]
So, I justed tested the default installation and it worked for both Disk and MySQL checks. But for memcached, despite the fact that it seems to be running the string used in the check it doesn't exist in the result of the memcached service output. I looked into a local older version of Homestead, an older ubuntu server instantiated by Forge and a new server instantiated by Forge. All of them had a result similar to the one below: 

```
service memcached status
● memcached.service - memcached daemon
   Loaded: loaded (/lib/systemd/system/memcached.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-12-19 18:34:58 -03; 1h 1min ago
 Main PID: 1215 (memcached)
    Tasks: 6
   Memory: 1.0M
      CPU: 144ms
   CGroup: /system.slice/memcached.service
           └─1215 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1
```

Is it possible that the memcached service check is not working out of the box anymore (maybe the output message changed) and nobody noticed yet? Or it might be my configuration?  I don't see a pull request related to that, but I'm assuming the adjustment below would fix it. 
```
if (str_contains($process->getOutput(), 'active (running)') ) {
```

**Comment by Pag-Man** [comment]
I have the same issue. Your proposed adjustment should fix the problem.

**Comment by freekmurze** [comment]
We'll handle this in #85 and #86
