### ISSUE TITLE
Laravel Scheduler

### ISSUE THREAD

**Issue by dqfan2012** [spatie/laravel-server-monitor#92]
Can this be used to monitor the Laravel scheduler? Thanks for your time!

**Comment by freekmurze** [comment]
Not out of the box. But you can manually create any check you want
https://docs.spatie.be/laravel-server-monitor/v1/monitoring-basics/writing-your-own-checks

**Comment by blorange2** [comment]
@freekmurze hi, have you moved your documentation for this package?

**Comment by freekmurze** [comment]
The docs are back online at: https://spatie.be/docs/laravel-server-monitor/v1/introduction
