### ISSUE TITLE
Error Driver [slack] not supported

### ISSUE THREAD

**Issue by SylvanoTombo** [spatie/laravel-server-monitor#96]
Error when run php artisan server-monitor:run-cheks.
It show InvalidArgumentException: Driver [slack] not supported

**Comment by freekmurze** [comment]
In modern version of Laravel the Slack driver is not installed by default. Refer to the Laravel docs to learn how to install the Slack driver.

**Comment by munkiepus** [comment]
It's not in the server-monitor docs anywhere saying that this needs to be installed, but it's as simple as running: 

`composer require laravel/slack-notification-channel`
